// Generated by CoffeeScript 1.12.7
(function() {
  var author, cube, quote, square;

  square = function(x) {
    return x * x;
  };

  cube = function(x) {
    return square(x) * x;
  };

  author = 'Wittgenstein';

  quote = "A picture is a fact. -- " + author;

}).call(this);
